version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: academic-journal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: academic_journal
      POSTGRES_USER: journal_user
      POSTGRES_PASSWORD: journal_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U journal_user -d academic_journal"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis (Optional - for caching and queues)
  redis:
    image: redis:7-alpine
    container_name: academic-journal-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data: