# Generated by Django 5.2.5 on 2025-08-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_unique_email_constraint'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_user_email',
        ),
    ]
